name = "Roots Drone Feed"
author = "Root"
prefix = "root_dronefeed"
mainprefix = "z"

[files]
include = [
    "mod.cpp",        
    "meta.cpp",       
    "LICENSE",
    "root_dronefeed_logo.paa",
    "README*.md",
]
exclude = [
    ".gitignore",
    ".editorconfig",
    "*.md",
    "*.json",
]

[properties]
author = "Root"
url = "https://github.com/A3-Root/Root_DroneFeed"

[lints.sqf.banned_commands]
options.banned = [
    "execVM",
]
options.ignore = [
    "addPublicVariableEventHandler",
]

[lints.sqf.var_all_caps]
options.ignore = [
    "ROOT_DRONEFEED_*",
]

[config.config_this_call]
enabled = true

[sqf.undefined]
enabled = true
options.check_orphan_code = true #off by default_config

[sqf.if_not_else]
enabled = true

[sqf.shadowed]
enabled = true

[sqf.not_private]
enabled = true

[sqf.short_circuit_bool_var]
enabled = true

[version]
git_hash = 0 # Disabled
